[package]
name = "eloquent_core"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tjardoo/eloquent-rs"
description = "Core query builder expressions and tools."

[dependencies]
