[package]
name = "eloquent_core"
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tjardoo/eloquent-rs"
description = "Core query builder component for Eloquent."

[dependencies]
