[package]
name = "eloquent"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tjardoo/eloquent-rs"
description = "An enjoyable way of interacting with the database."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
